//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Invoice
    {
        public int pkID { get; set; }
        public int fkUserID { get; set; }
        public int fkProductID { get; set; }
        public bool status { get; set; }
        public string transID { get; set; }
        public string trackingID { get; set; }
        public int factorNumber { get; set; }
    
        public virtual Table_Products Table_Products { get; set; }
        public virtual Table_Users Table_Users { get; set; }
    }
}
